name: example5
on: [push]
env:
  WORK_ON: Github Actions
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
       - run: echo "Hello world" > output.txt

       - name: Upload output file
         uses: actions/upload-artifact@v3
         with:
           name: output-log-file
           path: output.txt

       - run: echo "The test job has been completed!"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
            name: output-log-file

      - run: cat output-log-file

      - run: echo "The lint job has been completed!"
